spring.datasource.url=${DB_URL_NS}
spring.datasource.username=${DB_USERNAME_NS}
spring.datasource.password=${DB_PASSWORD_NS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=orchestration_prod

spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.default-schema=orchestration_prod
spring.flyway.schemas=orchestration_prod
spring.flyway.baseline-on-migrate=true