spring.application.name=orchestration-service
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info,metrics
spring.main.web-application-type=servlet

spring.jpa.open-in-view=false

# Habilita Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui

# log para ver se o springdoc ligou
logging.level.org.springdoc=DEBUG
# INFO

