spring.application.name=match-service
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info,metrics

spring.jpa.open-in-view=false

# Habilita Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# log para ver se o springdoc ligou
logging.level.org.springdoc=INFO

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false